server:
  port: 8080
  
spring:
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:h2:mem:shopbill
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false 
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
    hibernate:
      ddl-auto: update
 
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs: 
    enabled: true
  packages-to-scan: com.shop.bill